TARGET_ARCH_VARIANT:=x86
TARGET_PRODUCT=tina
HOST_BUILD_TYPE=release
TARGET_BUILD_TYPE=debug
BUILD_TINY_ANDROID=false
BUILD_STANDALONE_EMULATOR=true
BUILD_EMULATOR_OPENGL=false
BOARD_GPU_DRIVERS :=i915g swrast  i915
