
TMP1=gggg
TMP1=gggg2
#$(warning $(TMP1)  $(HE))
#$(warning shell ls $(1) $(2))

define func 
S: TMP1 += $(1)
HE +=345
NAME=$(1)
SP= -Dsefefe=\"$$(NAME)\"
endef

E= sp 
EE=varialb1$(strip $(E))_plugin

$(eval $(call func,hell,varialb1))
#s:=$(call func,"hell",varialb1)
$(warning $(SP))

HAVE_A=yes
ifdef HAVE_A
#$(warning HAVE_A)
endif

vpath %.mk ~/tmp/tmp

VPATH = /home/gwj/tmp/tmp
all: test.mk   |a.c 
	num=`ls`
	echo pwd "$$num" gggggggggg
	@echo $< ssss $^ 
	@echo $(MK)

sall:$(filter-out examples/C%,$(shell find examples)) test
	s=`ls`
	line=`ls `
	echo  $$line
	echo $$s
	@echo $(HE)

.PHONY:test.mk
test:test.mk | clean 
	echo $^
	$(eval MK=$^)
clean:
